#!/bin/bash
echo "======"
command=$1
echo "-----"
arguments="${@:2}"
echo "++++++"
basedir=$(dirname "$0")
pwd=$(pwd)
echo $command
echo $arguments
allowed="train test decode data sweep"

if ! [[ $allowed =~ (^|[[:space:]])"$command"($|[[:space:]]) ]]; then
  echo "ERROR: unknown command $command"
  exit 1
fi

python nabu/scripts/prepare_$command.py $arguments
